# Since we use custom test script, disable the default build action
build: false


# The Rust target platforms
platform:
  - thumbv6m-none-eabi


# The Rust feature matrix
configuration:
  - --features=alarm0
  - --features=alarm1
  - --features=alarm2
  - --features=alarm3
  - --features=init16,alarm0
  - --features=init16,alarm1
  - --features=init16,alarm2
  - --features=init16,alarm3


# General environment vars
environment:
  # Promote warnings to errors
  RUSTFLAGS: -D warnings


# Fail fast if one job in the matrix fails
matrix:
  fast_finish: true


# Build library
for:
  - environment:
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
    install:
      - curl https://sh.rustup.rs -sSf -o rustup-init.sh
      - sh rustup-init.sh -y --default-host x86_64-unknown-linux-gnu
      - source $HOME/.cargo/env
      - rustup target add "$PLATFORM"
    test_script:
      # Only build as we do not emulate the RP2040 to really run the code
      - cargo build --verbose --no-default-features $CONFIGURATION
      - cargo build --verbose --release --no-default-features $CONFIGURATION
